test: Migrate CI to GtiHub [SDK-4450]
auth0/nextjs-auth0 pull request #1437
Opened 2023-09-18 05:33 UTC by evansims

### 📋 Changes

This pull request replaces our current CircleCI continuous integration suite for auth0-react with a new workflow using GitHub Actions.

### 📎 References

Please see internal ticket SDK-4450.

### 🎯 Testing

This pull request replaces our continuous integration suite with one built in GitHub's native Actions ecosystem. It aligns with other migrations taking place across our repositories.

2023-09-18 15:23 UTC, frederikprijck submitted a review, later dismissed

2023-09-18 15:23 UTC, frederikprijck commented on .github/workflows/publish.yml
> +          cache: npm
We should set the registry-url to npm here, else it wont use authentication. See:

- https://github.com/actions/setup-node/blob/main/src/main.ts#L59-L61
- https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry

We encountered this with lock and fixed it: https://github.com/auth0/lock/pull/2445

2023-09-18 18:23 UTC, evansims commented
@adamjmcgrath I am unable to get `npm test` to work on either the CI migration or my local machine. Could you please take a look?

2023-09-18 19:10 UTC, frederikprijck commented
With @adamjmcgrath being off, I'll look into this.

2023-09-18 19:51 UTC, evansims commented
@frederikprijck Great, thanks. (FWIW, regarding your last commit, it already builds before running tests; see the `build` job the `unit` job `need`s beforehand.)

2023-09-25 05:35 UTC, evansims commented
@adamjmcgrath All migrated tests appear to be passing successfully with the workflows today. Uncertain why they hadn't worked previously, the error messages were rather confusing and vague.

CircleCI test is also randomly busted, it appears, so doesn't look related to anything to do with the migration.

That being the case, PR is ready for your review, thanks!

2023-10-02 07:41 UTC, adamjmcgrath requested changes
@evansims - I'm still seeing failed tests even though the "Run Unit Tests" job is reporting as successful 

<img width="956" alt="image" src="https://github.com/auth0/nextjs-auth0/assets/1299658/0e24a289-7e67-46c8-8a11-6b7575577e91">

Will take a look at the tests when I have some time

2023-10-12 13:22 UTC, adamjmcgrath commented
Unit tests are passing on GH Actions, just need to investigate why Browserstack tests aren't running

2023-10-13 12:59 UTC, merged