Allow setting redirect_uri at runtime on the callback handler just like it's allowed on the login handler
auth0/nextjs-auth0 pull request #298
Opened 2021-02-18 02:28 UTC by mariano

### Description

While there is currently a way to specify at runtime the `redirect_uri` used within the login handler (thus overriding whatever's defined in `process.env.AUTH0_BASE_URL`), the same cannot be done from within the callback handler, resulting in an `unauthorized_client` bad request error indicating the mismatch between 

This lack of consistency is evident in [login.ts](https://github.com/auth0/nextjs-auth0/blob/beta/src/auth0-session/handlers/login.ts#L26) where `LoginOptions.authorizationParams.redirect_uri` takes precedence over building the redirect url out of the juxtaposition of `config.baseURL` and `config.routes.callback`, while on [callback.ts](https://github.com/auth0/nextjs-auth0/blob/beta/src/auth0-session/handlers/callback.ts#L31) no such possibility to override exists and thus the redirect url can only be `urlJoin(config.baseURL, config.routes.callback)`.

This PR introduces a new option on `CallbackOptions` to allow an optional `redirect_uri` to be used. Using it makes it very easy to allow through `[...auth0].tsx` to use a different redirect URI at runtime. For example we can specify the return url at runtime by overriding the `login` and `callback` handlers:

```typescript
import { handleAuth, handleCallback, handleLogin } from '@auth0/nextjs-auth0';
import { NextApiRequest } from 'next';

export default handleAuth({
  async login(req, res) {
    const baseUrl = "http://messi:3000";
    const options = {
      authorizationParams: {
        redirect_uri: `${baseUrl}/api/auth/callback`
      },
      returnTo: `${baseUrl}/dashboard`
    };

    try {
      await handleLogin(req, res, options);
    } catch (error) {
      res.status(error.status || 400).end(error.message);
    }
  },

  async callback(req, res) {
    const baseUrl = "http://messi:3000";
    const options = {
      redirect_uri: `${baseUrl}/api/auth/callback`
    };

    try {
      await handleCallback(req, res, options);
    } catch (error) {
      res.status(error.status || 400).end(error.message);
    }
  }
});
```

### References

There were other tickets (#108, #154) that either directly or indirectly referenced this problem, mostly within the context of a Vercel implementation. We have experienced this ourselves while deploying a multi-tenant (wildcard subdomain) auth0 app to vercel.

This PR would fix #295.

### Testing

I've introduced a test case to ensure `CallbackOptions.redirect_uri` can be specified at runtime.

To test this in a real application just set your `AUTH0_BASE_URL` environment variable to one host (for example `http://localhost:3000`) and then modify that URL on the login handler through `authorizationParams.redirect_uri` to a different one (that's handle by the same nextjs app, such as `http://messi:3000`). Without this PR, after logging in on auth0 and being sent back to the nextjs app to handle the oauth callback, it'll consistently fail with a bad request `unauthorized_client (The redirect URI is wrong. You sent http://localhost:3000, and we expected http://messi:3000)`.

2021-02-18 09:32 UTC, adamjmcgrath requested changes
lgtm, just need to add it to the Next handler options

2021-02-18 09:32 UTC, adamjmcgrath commented on src/auth0-session/handlers/callback.ts
> +  redirectUri?: string;
Can you also add this option to https://github.com/auth0/nextjs-auth0/blob/main/src/handlers/callback.ts#L71-L73 ?

2021-02-18 11:44 UTC, mariano commented
> lgtm, just need to add it to the Next handler options

Just did, sorry I've missed that

2021-02-18 11:58 UTC, adamjmcgrath approved these changes

2021-02-18 11:58 UTC, merged

2021-02-18 11:58 UTC, adamjmcgrath commented
Thanks @mariano!

2021-02-18 12:04 UTC, adamjmcgrath commented
D'oh sorry @mariano,  could you raise this against `main` branch? We're not using `beta` any more

2021-02-18 12:20 UTC, adamjmcgrath commented
@mariano - actually don't worry, have raised #302

2021-02-18 12:33 UTC, mariano commented
> @mariano - actually don't worry, have raised #302

I was unsure which branch to use; thanks for taking care of it

2021-02-18 18:58 UTC, mariano commented
@adamjmcgrath sorry to keep bugging you, but are there plans for releasing a new npm version containing this fix? It is a limitation that prevents multi-tenant nextjs apps from working with auth0, so imho maybe it deserves a release? 

I did try forcing `package.json` to point to the main commit with:

`"@auth0/nextjs-auth0": "github:auth0/nextjs-auth0#7d7d4a9c9a8d5aa5bb86556f0dc4b2d7fe2e6ad8"`

and while yarn does install it properly it fails during build time while trying to resolve the `@auth0/nextjs-auth0` import references

2021-02-19 12:55 UTC, adamjmcgrath commented
@mariano - no worries, I'll do a release early next week

> I did try forcing package.json to point to the main commit with:

You need to build the `src`so this wont work, something like the following (untested) would:

```sh
$ git clone https://github.com/auth0/nextjs-auth0.git
$ cd nextjs-auth0
$ npm install
$ npm version 1.0.0-mariano.0 --no-git-tag-version # give it a unique version name so your npm install wont hit the cache for `1.0.0`
$ npm pack # this will build the src and package it in a tgz for you
$ cd ../your/next/app
$ npm install ../path/to/auth0-nextjs-auth0-1.0.0-mariano.0.tgz
```

2021-02-19 18:40 UTC, mariano commented
@adamjmcgrath Of course that did it. You are awesome. I don't play with frontend often, so pardon my cluelessness :)