Mw
auth0/nextjs-auth0 pull request #815
Opened 2022-09-09 15:35 UTC by adamjmcgrath

- [ ] All new/changed/fixed functionality is covered by tests (or N/A)
- [ ] I have added documentation for all new/changed functionality (or N/A)

### 📋 Changes

Added a new `withMiddlwareAuthRequired` helper, to protect routes using middleware.

To protect all your routes:

```js
// middleware.js
import { withMiddlewareAuthRequired } from '@auth0/nextjs-auth0/middleware';

export default withMiddlewareAuthRequired();
```

To protect specific routes:
```js
// middleware.js
import { withMiddlewareAuthRequired } from '@auth0/nextjs-auth0/middleware';

export default withMiddlewareAuthRequired();

export const config = {
  matcher: '/about/:path*',
}
```
For more info see: https://nextjs.org/docs/advanced-features/middleware#matching-paths

To run custom middleware for authenticated users:
```js
// middleware.js
import { withMiddlewareAuthRequired, getSession } from '@auth0/nextjs-auth0/middleware';
export default withMiddlewareAuthRequired(async function middleware(req) {
  const res = NextResponse.next();
  const user = await getSession(req, res);
  res.cookies.set('hl', user.language);
  return res;
});
```

### 📎 References

See https://github.com/auth0/nextjs-auth0/issues/525
https://nextjs.org/docs/advanced-features/middleware

### 🎯 Testing

Run kitchen-sink example app
Visit http://localhost:3000/profile-mw

2022-09-09 15:39 UTC, adamjmcgrath commented on package.json
> +      "!<rootDir>/src/auth0-session/session-cache.ts"
New coverage instrumenter c8 doesn't like files with only TS definitions. (was needed because istanbul instrumented code doesn't run on edge-runtime)

2022-09-09 15:42 UTC, adamjmcgrath commented on src/handlers/callback.ts
> +const idTokenValidator =
Whitespace changes from `eslint --fix`

2022-09-09 18:08 UTC, Widcket commented on src/helpers/with-middleware-auth-required.ts
> + * Protect your pages with Next.js Middleware. eg
```suggestion
 * Protect your pages with Next.js Middleware. For example:
```
The docs guidelines suggest not to use latin abbreviations.

2022-09-09 18:10 UTC, Widcket commented on src/helpers/with-middleware-auth-required.ts
> + * }
```suggestion
 * };
```

2022-09-12 10:12 UTC, adamjmcgrath commented on src/auth0-session/session-cache.ts
> +  create(req: unknown, res: unknown, session: { [key: string]: any }): Promise<void>;
Good point, I can use generics here 👍

2022-09-12 13:59 UTC, Widcket approved these changes

2022-09-12 14:58 UTC, adamjmcgrath commented on package.json
> +    "middleware.js",
hmm, good point - I didn't realise you had to do that. Will fix

2022-09-12 22:32 UTC, Widcket approved these changes

2022-09-12 23:21 UTC, Widcket commented on package.json
> +    "middleware.js",
You also have to include the typings file here –otherwise it will not be present in the package because it's not in side src.

2022-09-12 23:22 UTC, Widcket requested changes
Sorry, just noticed that the typings file also needs to be included in the `files` array in the `package.json` –otherwise it will not be present in the package because it's not inside `src`.

2022-09-13 06:24 UTC, adamjmcgrath commented on package.json
> +    "middleware.js",
d'oh, yep - good point 👍

2022-09-13 06:38 UTC, Widcket approved these changes

2022-09-13 07:12 UTC, merged

2022-10-04 19:28 UTC, Jared-Dev commented
Not sure if this is the correct place to put this, but I believe I'm seeing some typing issues with the latest version of Next on the `vNext` branch.

When using a copy/paste example from the Next docs I'm seeing the below.
<img width="457" alt="image" src="https://user-images.githubusercontent.com/1476753/193907167-46501696-32d9-42a5-b33d-63ea0229e538.png">
<img width="693" alt="image" src="https://user-images.githubusercontent.com/1476753/193907241-46c0022f-266d-4316-8a13-4d36156ba605.png">

2022-10-06 12:44 UTC, adamjmcgrath commented
Hi @Jared-Dev - thanks for testing this out!

Looks like you're using `npm link` and the version of next installed in `Sites/packages/nextjs-auth0` is incompatible with the version installed in `Sites/ox-portal/` - if you use `npm pack` to package the dependency (or install from npm when the beta is available - v soon) you will only have one `next` dependency so shouldn't run into this problem.

2022-10-20 21:52 UTC, divmgl commented on src/helpers/with-middleware-auth-required.ts
> +        return NextResponse.next({ ...res, headers });
This is not working as intended for redirects. We'll need a test around this as well. See https://github.com/auth0/nextjs-auth0/issues/874.

```suggestion
        return NextResponse.next({ ...res, headers, status: res.status });
```